tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-bg": "#101417",
        "brand-sage": "#b2cdb9",
        "brand-slate": "#aacbdf",
        "brand-cream": "#cfc6ae",
        "brand-card": "#1a1f23",
        "surface-container-low": "#181c1f",
        surface: "#101417",
        "on-primary": "#1e3527",
        "inverse-on-surface": "#2d3134",
        secondary: "#aacbdf",
        "primary-container": "#8ca693",
        "on-primary-container": "#243c2d",
        error: "#ffb4ab",
        primary: "#b2cdb9",
        "on-secondary-fixed-variant": "#2a4b5b",
        outline: "#8c928c",
        "on-secondary-container": "#9cbdd1",
        "outline-variant": "#424843",
        "primary-fixed-dim": "#b2cdb9",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#4c6453",
        "secondary-container": "#2d4d5e",
        "tertiary-fixed-dim": "#cfc6ae",
        "secondary-fixed": "#c6e7fc",
        "surface-variant": "#313538",
        "surface-container-lowest": "#0b0f11",
        "surface-container-high": "#262a2d",
        "surface-container-highest": "#313538",
        "surface-tint": "#b2cdb9",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#4c4634",
        "surface-dim": "#101417",
        "on-primary-fixed-variant": "#344c3d",
        "on-secondary": "#113444",
        "on-error": "#690005",
        "on-background": "#e0e3e7",
        "surface-bright": "#363a3d",
        "on-tertiary-fixed": "#201b0c",
        "on-primary-fixed": "#082013",
        "on-surface-variant": "#c2c8c1",
        "tertiary-fixed": "#ece2c9",
        tertiary: "#cfc6ae",
        "on-tertiary-container": "#3b3625",
        "on-tertiary": "#35301f",
        "primary-fixed": "#cee9d4",
        "on-surface": "#e0e3e7",
        "surface-container": "#1c2023",
        "on-secondary-fixed": "#001e2b",
        "tertiary-container": "#a79f89",
        "secondary-fixed-dim": "#aacbdf",
        "inverse-surface": "#e0e3e7",
        background: "#101417",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "max-width": "1200px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        "label-md": ['"Silkscreen"', "sans-serif"],
        "headline-lg-mobile": ['"Geist Pixel"', "sans-serif"],
        "headline-lg": ['"Geist Pixel"', "sans-serif"],
        "headline-xl": ['"Geist Pixel"', "sans-serif"],
        "body-sm": ['"Geist Pixel"', "sans-serif"],
        "body-md": ['"Geist Pixel"', "sans-serif"],
        sans: ['"Geist Pixel"', "sans-serif"],
        mono: ['"Silkscreen"', "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "12px",
          {
            lineHeight: "1",
            fontWeight: "500",
          },
        ],
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "1.2",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "1.2",
            fontWeight: "600",
          },
        ],
        "headline-xl": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "1.5",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.6",
            fontWeight: "400",
          },
        ],
      },
      borderWidth: {
        1: "1px",
      },
      boxShadow: {
        offset: "4px 4px 0px 0px rgba(178, 205, 185, 0.2)",
        "offset-hover": "6px 6px 0px 0px rgba(178, 205, 185, 0.3)",
      },
    },
  },
};
